testblock_nav:
  time:
    - groundtruth: 25.5
      groundtruth_epsilon: 1.0
  goal:
    - topic: /move_base/goal
      groundtruth: 0.0
      groundtruth_epsilon: 0.3
  jerk:
    - topic: /base/odometry_controller/odometry
      groundtruth: 0.0
      groundtruth_epsilon: 4.0
  path_length:
    - root_frame: /map
      measured_frame: /base_link
      groundtruth: 8.5
      groundtruth_epsilon: 0.3
#      groundtruth_angle_epsilon: 20.0 # [degree]
#      groundtruth_angle: 0.0 # [degree]